{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b93eab8b-82e1-4659-a696-2fe31bc14193",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2bbc2cd7-f0a8-4e61-9d33-a72fa33ce9a9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8d1b91cf-b968-431e-8f19-a0e25413b233",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV\n",
    "from sklearn.metrics import classification_report, accuracy_score\n",
    "from imblearn.over_sampling import ADASYN, BorderlineSMOTE\n",
    "from imblearn.pipeline import Pipeline as ImbPipeline\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.svm import SVC\n",
    "from lightgbm import LGBMClassifier\n",
    "from xgboost import XGBClassifier\n",
    "from sklearn.utils.class_weight import compute_sample_weight\n",
    "from sklearn.ensemble import VotingClassifier\n",
    "\n",
    "# 1. Cost‑Sensitive Wrapper for XGBoost\n",
    "class CostSensitiveXGBClassifier(XGBClassifier):\n",
    "    def fit(self, X, y, **kwargs):\n",
    "        sample_weight = compute_sample_weight(class_weight='balanced', y=y)\n",
    "        return super().fit(X, y, sample_weight=sample_weight, **kwargs)\n",
    "\n",
    "\n",
    "\n",
    "# 3. Load & Split Data\n",
    "X = pd.read_csv('X_train_cleaned.csv')\n",
    "y = pd.read_csv('y_train_cleaned.csv')['label']\n",
    "X_train, X_val, y_train, y_val = train_test_split(\n",
    "    X, y, test_size=0.2, stratify=y, random_state=42\n",
    ")\n",
    "num_classes = len(np.unique(y_train))\n",
    "\n",
    "# 4. Define Oversampling + Model Pipelines with Best Params\n",
    "\n",
    "# 4a. ADASYN + Logistic Regression (C=0.215, lbfgs, max_iter=2000)\n",
    "pipe_lr = ImbPipeline(steps=[\n",
    "    ('adasyn', ADASYN(random_state=42, n_neighbors=3)),\n",
    "    ('lr', LogisticRegression(\n",
    "        C=0.215,\n",
    "        solver='lbfgs',\n",
    "        class_weight='balanced',\n",
    "        max_iter=2000,\n",
    "        random_state=42\n",
    "    ))\n",
    "])\n",
    "\n",
    "# 4b. BorderlineSMOTE + SVM (C=100, kernel=rbf, gamma=auto)\n",
    "pipe_svm = ImbPipeline(steps=[\n",
    "    ('bsmote', BorderlineSMOTE(random_state=42, k_neighbors=3)),\n",
    "    ('svm', SVC(\n",
    "        C=100,\n",
    "        kernel='rbf',\n",
    "        gamma='auto',\n",
    "        class_weight='balanced',\n",
    "        probability=True,\n",
    "        random_state=42\n",
    "    ))\n",
    "])\n",
    "\n",
    "# 4c. ADASYN + LightGBM (num_leaves=80, max_depth=7, lr=0.05, n_estimators=300, feature_fraction=0.7)\n",
    "pipe_lgbm = ImbPipeline(steps=[\n",
    "    ('adasyn', ADASYN(random_state=42, n_neighbors=3)),\n",
    "    ('lgbm', LGBMClassifier(\n",
    "        class_weight='balanced',\n",
    "        num_leaves=80,\n",
    "        max_depth=7,\n",
    "        learning_rate=0.05,\n",
    "        n_estimators=300,\n",
    "        feature_fraction=0.7,\n",
    "        random_state=42\n",
    "    ))\n",
    "])\n",
    "\n",
    "# 4d. BorderlineSMOTE + Cost‑Sensitive XGBoost (max_depth=5, lr=0.1, n_estimators=200, subsample=0.8, colsample_bytree=0.8)\n",
    "pipe_xgb = ImbPipeline(steps=[\n",
    "    ('bsmote', BorderlineSMOTE(random_state=42, k_neighbors=3)),\n",
    "    ('xgb', CostSensitiveXGBClassifier(\n",
    "        max_depth=5,\n",
    "        learning_rate=0.1,\n",
    "        n_estimators=200,\n",
    "        subsample=0.8,\n",
    "        colsample_bytree=0.8,\n",
    "        objective='multi:softprob',\n",
    "        num_class=num_classes,\n",
    "        eval_metric='mlogloss',\n",
    "        random_state=42\n",
    "    ))\n",
    "])\n",
    "\n",
    "\n",
    "\n",
    "# 6. Build Ensemble with tuned branches\n",
    "ensemble = VotingClassifier(\n",
    "    estimators=[\n",
    "        ('lr', pipe_lr),\n",
    "        ('svm', pipe_svm),\n",
    "        ('lgbm', pipe_lgbm),\n",
    "        ('xgb', pipe_xgb)\n",
    "    ],\n",
    "    voting='soft'\n",
    ")\n",
    "\n",
    "# 7. Train Ensemble\n",
    "ensemble.fit(X_train, y_train)\n",
    "\n",
    "# 8. Evaluate on Validation Set\n",
    "y_pred = ensemble.predict(X_val)\n",
    "print(\"Ensemble Validation Accuracy:\", accuracy_score(y_val, y_pred))\n",
    "print(\"Ensemble Classification Report:\")\n",
    "print(classification_report(y_val, y_pred, zero_division=0))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8a001585-90c4-4f9f-97fc-3e061571c341",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
